# Top level configuration
ores:
  score_processor: local_celery
  wsgi:
    application_root: ""
    url_prefix: ""

# Caching options
score_caches:
  local_redis:
    class: ores.score_caches.Redis
    host: localhost
    prefix: ores
  lru:
    class: ores.score_caches.LRU

# Score processing options
score_processors:
  defaults:
    score_cache: local_redis
    scoring_contexts:
      - enwiki
  local_celery:
    class: ores.score_processors.Celery
    BROKER_URL: redis://localhost
    CELERY_RESULT_BACKEND: redis://localhost
    timeout: 5 # seconds
  timeout:
    class: ores.score_processors.Timeout
    timeout: 5 # seconds

# Scoring contexts
scoring_contexts:
  enwiki:
    extractor: enwiki_api
    scorer_models:
      reverted: enwiki_revert

# Available feature extractors
extractors:
  defaults:
    class: revscoring.extractors.APIExtractor
    user_agent: Object Revision Evaluation Service (local development)
  enwiki_api:
    url: http://en.wikipedia.org/w/api.php

# Scorer models
scorer_models:
  defaults:
    class: revscoring.scorer_models.MLScorerModel
  enwiki_revert:
    model_file: models/enwiki.reverted.linear_svc.model
